### ISSUE TITLE
(Instance) redlib.perennialte.ch

### ISSUE THREAD

**Issue by perennialtech** [redlib-org/redlib-instances#1]
### Country

AU

### Cloudflare enabled?

Yes

### What type of instance is it?

HTTPS

### URL

https://redlib.perennialte.ch

**Comment by sigaloid** [comment]
I've added this manually in https://github.com/redlib-org/redlib-instances/commit/a7bd3d095749282f67e07c6704ffaac337e031e6, thanks for contributing your instance!
