### ISSUE TITLE
Add New instance https://redlib.frontendfriendly.xyz/

### ISSUE THREAD

**Issue by toyboatcash** [redlib-org/redlib-instances#41]
Add New instance at https://redlib.frontendfriendly.xyz/ and at http://redlib.wsuno6lnjdcsiok5mrxvl6e2bdex7nhsqqav6ux7tkwrqiqnulejfbyd.onion/

**Comment by sigaloid** [comment]
Because you proxy traffic across the world, I'm going to use country code XX - if you'd like this changed let me know!
